---

parser: babel-eslint

plugins:
  - jest
  - import
  - babel

env:
  es2020: true
  browser: true

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'


parserOptions:
  ecmaVersion: 2020
  sourceType: module

rules:
  no-console: 0
